%{?!ros_distro:%global ros_distro rolling}
%global pkg_name rmw_implementation
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}
%global _bloom_disable_groups 1

Name:           ros-rolling-rmw-implementation
Version:        3.1.5
Release:        4%{?dist}
Summary:        ROS %{pkg_name} package

License:        Apache License 2.0
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  bloom-rpm-macros
BuildRequires:  cmake

# We need more than one RMW present to build this package
# Choose the default and one other
BuildRequires:  ros-%{ros_distro}(rmw_fastrtps_cpp)(devel)
BuildRequires:  ros-%{ros_distro}(rmw_fastrtps_dynamic_cpp)(devel)

%{?bloom_package}

%description
Proxy implementation of the ROS 2 Middleware Interface.


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
Provides:       %{name}%{?_isa} = %{version}-%{release}
Requires:       %{name}-runtime%{?_isa} = %{version}-%{release}
Suggests:       ros-%{ros_distro}(rmw_fastrtps_cpp)(devel)
Requires:       ros-%{ros_distro}(rmw_implementation_packages)(devel)(member)

%description devel
Proxy implementation of the ROS 2 Middleware Interface.


%package runtime
Release:        %{release}
Summary:        %{summary}
Suggests:       ros-%{ros_distro}(rmw_fastrtps_cpp)
Requires:       ros-%{ros_distro}(rmw_implementation_packages)(member)

%description runtime
Proxy implementation of the ROS 2 Middleware Interface.


%prep
%autosetup -p1


%generate_buildrequires
%bloom_buildrequires -g


%build
%cmake \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="%{bloom_prefix}" \
    -DAMENT_PREFIX_PATH="%{bloom_prefix}" \
    -DCMAKE_PREFIX_PATH="%{bloom_prefix}" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif

%cmake3_build


%install
%cmake_install


%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C %{__cmake_builddir} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
CTEST_OUTPUT_ON_FAILURE=1 \
    %cmake_build $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif


%files devel
%dir %{bloom_prefix}
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
%{bloom_prefix}


%changelog
* Tue Apr 21 2026 William Woodall <william@openrobotics.org> - 3.1.5-4
- Autogenerated by Bloom
